# 端口
server:
    port: 8081

spring: 
    # sa-token配置
    sa-token: 
        # token名称（同时也是cookie名称）
        token-name: satoken
        # token有效期，单位s 默认30天，-1为永不过期   
        timeout: 2592000
        # 在多人登录同一账号时，是否共享会话（为true时共用一个，为false时新登录挤掉旧登录）
        is-share: true
        # 是否在cookie读取不到token时，继续从请求header里继续尝试读取 
        is-read-head: true
        #  是否在header读取不到token时，继续从请求题参数里继续尝试读取 
        is-read-body: true
        # 是否在初始化配置时打印版本字符画
        is-v: true
        