# 端口
server:
    port: 8081

spring: 
    # sa-token配置
    sa-token: 
        # token名称（同时也是cookie名称）
        token-name: satoken
        # token有效期，单位s 默认30天，-1为永不过期   
        timeout: 2592000
        # 在多人登录同一账号时，是否共享会话（为true时共用一个，为false时新登录挤掉旧登录）
        is-share: true
        # 是否在cookie读取不到token时，继续从请求header里继续尝试读取 
        is-read-head: true
        #  是否在header读取不到token时，继续从请求题参数里继续尝试读取 
        is-read-body: true
        # 是否在初始化配置时打印版本字符画
        is-v: true
        
          
    # redis配置 
    redis:
        # Redis数据库索引（默认为0）
        database: 1
        # Redis服务器地址
        host: 127.0.0.1
        # Redis服务器连接端口
        port: 6379
        # Redis服务器连接密码（默认为空）
        password: 
        # 连接池最大连接数（使用负值表示没有限制）
        pool:
            maxActive: 20
            # 连接池最大阻塞等待时间（使用负值表示没有限制）
            maxWait: -1
            # 连接池中的最大空闲连接
            maxIdle: 8
            # 连接池中的最小空闲连接
            minIdle: 1
        # 连接超时时间（毫秒）
        timeout: 0
        
        